### ISSUE TITLE
Cannot create Conda environment

### ISSUE THREAD

**Issue by cerkezoglu** [pnnl/neuromancer#6]
I am using W10 with GTX 1050, installed Cuda 11.6.2 from [https://developer.nvidia.com/cuda-11-6-2-download-archive](url)
when I try to create an environment on conda with the command `conda env create -f windows_env.yml ` just as instructed:
I face the following error:
```
Collecting package metadata (repodata.json): done
Solving environment: done

Downloading and Extracting Packages

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Installing pip dependencies: \ Ran pip subprocess with arguments:
['C:\\Users\\abdul\\anaconda3\\envs\\neuromancer\\python.exe', '-m', 'pip', 'install', '-U', '-r', 'C:\\Users\\abdul\\Development\\GithubPullLibraries\\neuromancer\\condaenv.72d89e9z.requirements.txt', '--exists-action=b']
Pip subprocess output:
Collecting torch-scatter==2.0.9
  Using cached torch_scatter-2.0.9.tar.gz (21 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'

Pip subprocess error:
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\abdul\AppData\Local\Temp\pip-install-qedr1lz1\torch-scatter_67744a4e9c9445c3827c6dce08510523\setup.py", line 8, in <module>
          import torch
        File "C:\Users\abdul\anaconda3\envs\neuromancer\lib\site-packages\torch\__init__.py", line 128, in <module>
          raise err
      OSError: [WinError 182] The operating system cannot run %1. Error loading "C:\Users\abdul\anaconda3\envs\neuromancer\lib\site-packages\torch\lib\shm.dll" or one of its dependencies.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

failed

CondaEnvException: Pip failed
```
Any help ? Thanks

**Comment by markosvec** [comment]
I had the same problem. Have no idea what went wrong, but the problem is definitely with "Pytorch-Scatter" since conda install pytorch-scatter -c pyg didn't work either. However, I didn't have any luck with tracing the problem.

**Comment by cerkezoglu** [comment]
I have managed to find a way to install the package, it was the following the instructions of the [https://github.com/pnnl/neuromancer/blob/master/Documentation.pdf](url) Section 5.2.
I have executed: (Retrieved from: [https://pytorch.org/get-started/previous-versions/](url) )
`conda install pytorch==1.12.1 torchvision==0.13.1 torchaudio==0.12.1 cudatoolkit=11.6 -c pytorch -c conda-forge`
instead of this line:
`(neuromancer) $ conda install pytorch cudatoolkit=10.2 -c pytorch`

Now I cannot import `neuromancer` as namespace and access the submodules:
```
import neuromancer as nm
func = nm.blocks.MLP(insize=2, outsize=2, hsizes=[80] * 4)
```
Error:
```
AttributeError                            Traceback (most recent call last)
Cell In[2], line 3
      1 import neuromancer as nm
----> 3 func = nm.blocks.MLP(insize=2, outsize=2, hsizes=[80] * 4)

AttributeError: module 'neuromancer' has no attribute 'blocks'
```
But I can import the submodules individually:
```
import neuromancer.blocks 
import neuromancer.activations 
```

**Comment by drgona** [comment]
Hi all, it seems we have some issues with yml files.
For now, I would recommend following manual install following the instructions below:
https://github.com/pnnl/neuromancer#other-operating-system

Please let me know if this still fails.

**Comment by markosvec** [comment]
It fails for me on the line conda install pytorch-scatter -c pyg. I tried the suggestion which @cerkezoglu gave and successfully installed everything (replicated what he pointed out), but in that case I wasn't able to use neuromancer.constraints, so it doesn't really work. My guess is that pytorch-scatter has problems with pytorch distribution which automatically gets installed. And I have absolutely no idea why import neuromancer as nm doesn't work.

**Comment by cerkezoglu** [comment]
It fails for me on the line `conda install pytorch-scatter -c pyg` as well. @drgona

**Comment by drgona** [comment]
@markosvec @cerkezoglu thank you both! Not importing the main module after it gets installed is strange.
Assuming you have all the restrictions, you might want to give a shot running `python setup.py develop` command from the module's directory.
https://stackoverflow.com/questions/14295680/unable-to-import-a-module-that-is-definitely-installed

We will look at this and come back to you with a fix as soon as we have it.

**Comment by aarontuor** [comment]
We have released V1.3 with updated env.yml files and installation instructions and have removed torch-scatter as a dependency from neuromancer. You should have better results now.

**Comment by cerkezoglu** [comment]
I have tried to use `windows_env.yml` file on two different devices with w10 and w11, both responded same with the instruction line `conda install -c defaults intel-openmp -f ` ;

```
WARNING: The --force flag will be removed in a future conda release.
         See 'conda install --help' for details about the --force-reinstall
         and --clobber flags.


Collecting package metadata (current_repodata.json): failed
WARNING conda.exceptions:print_unexpected_error_report(1251): KeyError('pkgs_dirs')
Traceback (most recent call last):
  File "C:\Users\abdul\anaconda3\lib\site-packages\conda\exceptions.py", line 1129, in __call__
    return func(*args, **kwargs)
  File "C:\Users\abdul\anaconda3\lib\site-packages\conda\cli\main.py", line 86, in main_subshell
    exit_code = do_call(args, p)
  File "C:\Users\abdul\anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 93, in do_call
    return getattr(module, func_name)(args, parser)
  File "C:\Users\abdul\anaconda3\lib\site-packages\conda\notices\core.py", line 72, in wrapper
    return_value = func(*args, **kwargs)
  File "C:\Users\abdul\anaconda3\lib\site-packages\conda\cli\main_install.py", line 22, in execute
    install(args, parser, 'install')
  File "C:\Users\abdul\anaconda3\lib\site-packages\conda\cli\install.py", line 261, in install
    unlink_link_transaction = solver.solve_for_transaction(
  File "C:\Users\abdul\anaconda3\lib\site-packages\conda\core\solve.py", line 156, in solve_for_transaction
    unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
  File "C:\Users\abdul\anaconda3\lib\site-packages\conda\core\solve.py", line 199, in solve_for_diff
    final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
  File "C:\Users\abdul\anaconda3\lib\site-packages\conda\core\solve.py", line 304, in solve_final_state
    ssc = self._collect_all_metadata(ssc)
  File "C:\Users\abdul\anaconda3\lib\site-packages\conda\common\io.py", line 86, in decorated
    return f(*args, **kwds)
  File "C:\Users\abdul\anaconda3\lib\site-packages\conda\core\solve.py", line 467, in _collect_all_metadata
    index, r = self._prepare(prepared_specs)
  File "C:\Users\abdul\anaconda3\lib\site-packages\conda\core\solve.py", line 1061, in _prepare
    reduced_index = get_reduced_index(self.prefix, self.channels,
  File "C:\Users\abdul\anaconda3\lib\site-packages\conda\core\index.py", line 301, in get_reduced_index
    new_records = SubdirData.query_all(spec, channels=channels, subdirs=subdirs,
  File "C:\Users\abdul\anaconda3\lib\site-packages\conda\core\subdir_data.py", line 115, in query_all
    create_cache_dir()
  File "C:\Users\abdul\anaconda3\lib\site-packages\conda\core\subdir_data.py", line 737, in create_cache_dir
    cache_dir = join(PackageCacheData.first_writable().pkgs_dir, 'cache')
  File "C:\Users\abdul\anaconda3\lib\site-packages\conda\core\package_cache_data.py", line 158, in first_writable
    pkgs_dirs = context.pkgs_dirs
  File "C:\Users\abdul\anaconda3\lib\site-packages\conda\base\context.py", line 555, in pkgs_dirs
    fixed_dirs += user_data_dir(APP_NAME, APP_NAME),
  File "C:\Users\abdul\anaconda3\lib\site-packages\conda\_vendor\appdirs.py", line 67, in user_data_dir
    path = os.path.join(_get_win_folder(const), appauthor, appname)
  File "C:\Users\abdul\anaconda3\lib\site-packages\conda\_vendor\appdirs.py", line 265, in _get_win_folder_with_pywin32
    from win32com.shell import shellcon, shell
ImportError: DLL load failed while importing shell: The specified procedure could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\abdul\anaconda3\lib\site-packages\conda\exceptions.py", line 1249, in print_unexpected_error_report
    message_builder.append(get_main_info_str(error_report['conda_info']))
  File "C:\Users\abdul\anaconda3\lib\site-packages\conda\cli\main_info.py", line 237, in get_main_info_str
    info_dict['_' + key] = ('\n' + 26 * ' ').join(info_dict[key])
KeyError: 'pkgs_dirs'

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\abdul\anaconda3\lib\site-packages\conda\exceptions.py", line 1129, in __call__
        return func(*args, **kwargs)
      File "C:\Users\abdul\anaconda3\lib\site-packages\conda\cli\main.py", line 86, in main_subshell
        exit_code = do_call(args, p)
      File "C:\Users\abdul\anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 93, in do_call
        return getattr(module, func_name)(args, parser)
      File "C:\Users\abdul\anaconda3\lib\site-packages\conda\notices\core.py", line 72, in wrapper
        return_value = func(*args, **kwargs)
      File "C:\Users\abdul\anaconda3\lib\site-packages\conda\cli\main_install.py", line 22, in execute
        install(args, parser, 'install')
      File "C:\Users\abdul\anaconda3\lib\site-packages\conda\cli\install.py", line 261, in install
        unlink_link_transaction = solver.solve_for_transaction(
      File "C:\Users\abdul\anaconda3\lib\site-packages\conda\core\solve.py", line 156, in solve_for_transaction
        unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
      File "C:\Users\abdul\anaconda3\lib\site-packages\conda\core\solve.py", line 199, in solve_for_diff
        final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
      File "C:\Users\abdul\anaconda3\lib\site-packages\conda\core\solve.py", line 304, in solve_final_state
        ssc = self._collect_all_metadata(ssc)
      File "C:\Users\abdul\anaconda3\lib\site-packages\conda\common\io.py", line 86, in decorated
        return f(*args, **kwds)
      File "C:\Users\abdul\anaconda3\lib\site-packages\conda\core\solve.py", line 467, in _collect_all_metadata
        index, r = self._prepare(prepared_specs)
      File "C:\Users\abdul\anaconda3\lib\site-packages\conda\core\solve.py", line 1061, in _prepare
        reduced_index = get_reduced_index(self.prefix, self.channels,
      File "C:\Users\abdul\anaconda3\lib\site-packages\conda\core\index.py", line 301, in get_reduced_index
        new_records = SubdirData.query_all(spec, channels=channels, subdirs=subdirs,
      File "C:\Users\abdul\anaconda3\lib\site-packages\conda\core\subdir_data.py", line 115, in query_all
        create_cache_dir()
      File "C:\Users\abdul\anaconda3\lib\site-packages\conda\core\subdir_data.py", line 737, in create_cache_dir
        cache_dir = join(PackageCacheData.first_writable().pkgs_dir, 'cache')
      File "C:\Users\abdul\anaconda3\lib\site-packages\conda\core\package_cache_data.py", line 158, in first_writable
        pkgs_dirs = context.pkgs_dirs
      File "C:\Users\abdul\anaconda3\lib\site-packages\conda\base\context.py", line 555, in pkgs_dirs
        fixed_dirs += user_data_dir(APP_NAME, APP_NAME),
      File "C:\Users\abdul\anaconda3\lib\site-packages\conda\_vendor\appdirs.py", line 67, in user_data_dir
        path = os.path.join(_get_win_folder(const), appauthor, appname)
      File "C:\Users\abdul\anaconda3\lib\site-packages\conda\_vendor\appdirs.py", line 265, in _get_win_folder_with_pywin32
        from win32com.shell import shellcon, shell
    ImportError: DLL load failed while importing shell: The specified procedure could not be found.

`$ C:\Users\abdul\anaconda3\Scripts\conda-script.py install -c defaults intel-openmp -f`

  environment variables:
conda info could not be constructed.
KeyError('pkgs_dirs')
```
Tried the [Manual](https://github.com/pnnl/neuromancer#other-operating-system) installation instructions and had the issue of  [https://github.com/pytorch/pytorch/issues/72293](url). Solved the problem by running extra line on the conda environment `conda install -c defaults intel-openmp -f`.

**Comment by aarontuor** [comment]
This line, conda install -c defaults intel-openmp -f,  is now included in the manual install instructions (in a comment) and the windows_env.yml has been updated.
